spring:
  application:
    name: seata-account
  datasource:
    url: jdbc:mariadb://localhost:3306/account_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: Tomatos
    password: 20030503
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
server:
  port: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
#seata:
#  data-source-proxy-mode: XA
